genre_map = {
    "impressionist": "classical",
    "baroque": "classical",
    "romantic": "classical",
    "classical": "classical",
    "medieval": "classical",
    "chant": "classical",
    "minimalism": "classical",
    "wedding": "classical",
    "choral": "classical",
    "chamber": "classical",
    "opera": "classical",
    "early music": "classical",
    "avante-garde": "classical",
    "symphony": "classical",
    "orchestra": "classical",
    "christian": "classical",
    "gospel": "classical",
    "worship": "classical",

    "rock": "rock",
    "punk": "rock",
    "grunge": "rock",
    "metal": "rock",
    "post-rock": "rock",
    "post-punk": "rock",
    'british invasion': 'rock',

    "pop": "pop",
    "electropop": "pop",
    "synthpop": "pop",
    "dance-pop": "pop",
    "k-pop": "pop",
    "j-pop": "pop",
    "europop": "pop",

    "hip hop": "rap",
    "hip-hop": "rap",
    "rap": "rap",
    "trap": "rap",
    "boom bap": "rap",
    "crunk": "rap",

    "jazz": "jazz",
    "swing": "jazz",
    "bebop": "jazz",
    "fusion": "jazz",
    "big band": "jazz",

    "electronic": "electronic",
    "edm": "electronic",
    "house": "electronic",
    "techno": "electronic",
    "trance": "electronic",
    "dubstep": "electronic",
    "drum and bass": "electronic",
    "ambient": "electronic",
    "downtempo": "electronic",
    "chillwave": "electronic",
    "synthwave": "electronic",
    "electro": "electronic",
    "idm": "electronic",
    "trip hop": "electronic",
    "glitch": "electronic",

    "r&b": "r&b",
    "soul": "r&b",
    "neo-soul": "r&b",
    "funk": "r&b",
    "disco": "r&b",
    "quiet storm": "r&b",
    "new jack swing": "r&b",
    "motown": "r&b",
    
    "blues": "blues",

    "reggae": "reggae",
    "ska": "reggae",
    "rocksteady": "reggae",
    "dub": "reggae",
    "dancehall": "reggae",

    "country": "country",
    "bluegrass": "country",
    "honky tonk": "country",
    "alt-country": "country",
    "americana": "country",

    "folk": "folk",
    "singer-songwriter": "folk",
    "celtic": "folk",



    "alternative": "alternative",
    "indie": "alternative",



    "soundtrack": "soundtrack",
    "movie": "soundtrack",
    "game": "soundtrack",
    "musical": "soundtrack",
    "anime": "soundtrack",

}